import os
import random
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from dotenv import load_dotenv

load_dotenv()

def get_spotify_client():
    client_id = os.getenv('SPOTIPY_CLIENT_ID')
    client_secret = os.getenv('SPOTIPY_CLIENT_SECRET')
    
    if not client_id or not client_secret or client_id == 'YOUR_SPOTIFY_CLIENT_ID':
        return None
        
    try:
        # Use Client Credentials Flow (no user login required)
        auth_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
        sp = spotipy.Spotify(auth_manager=auth_manager)
        return sp
    except Exception as e:
        print(f"Failed to initialize Spotify client: {e}")
        return None

def get_dynamic_songs(mood, language, limit=10):
    """
    Fetches fresh songs from Spotify based on mood and language.
    Returns a list of dictionaries matching the app's internal format,
    falling back gracefully to returning [] on failure.
    """
    sp = get_spotify_client()
    if not sp:
        return []
        
    # Map app moods to Spotify search keywords
    mood_keywords = {
        'happy': 'happy upbeat',
        'sad': 'sad emotional heartbreak',
        'stress': 'calm relaxing peaceful chill',
        'angry': 'angry aggressive workout rock'
    }
    
    keyword = mood_keywords.get(mood.lower(), mood)
    
    # Formulate search query
    if language.lower() == 'english':
        query = f"{keyword} hits"
    else:
        query = f"{language} {keyword} songs"
        
    try:
        # Search for playlists matching the query
        results = sp.search(q=query, type='playlist', limit=5)
        playlists = results.get('playlists', {}).get('items', [])
        
        if not playlists:
            return []
            
        # Pick a random playlist from top 5 to keep it fresh
        target_playlist = random.choice([p for p in playlists if p is not None])
        
        # Get tracks from the chosen playlist
        playlist_tracks = sp.playlist_tracks(target_playlist['id'], limit=30)
        items = playlist_tracks.get('items', [])
        
        songs = []
        for item in items:
            track = item.get('track')
            if not track: continue
            
            # Extract main artist and track name
            artist_name = track['artists'][0]['name'] if track['artists'] else 'Unknown Artist'
            track_name = track['name']
            
            # Format title like "Song - Artist"
            full_title = f"{track_name} - {artist_name}"
            
            # We don't have youtube links for these, they will be generated by build_links
            songs.append({
                'mood': mood,
                'language': language,
                'song_title': full_title,
                'youtube_link': '' # Will be handled by the helper in app.py
            })
            
            if len(songs) >= limit:
                break
                
        # Shuffle the scraped songs
        random.shuffle(songs)
        return songs
        
    except Exception as e:
        print(f"Spotify API Error: {e}")
        return []

if __name__ == '__main__':
    # Test script
    songs = get_dynamic_songs('happy', 'telugu')
    print(f"Found {len(songs)} songs:")
    for s in songs:
        print(s['song_title'])
